# Generated by Django 3.2 on 2021-05-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210502_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowinsession',
            name='session_id',
            field=models.UUIDField(unique=True),
        ),
    ]
