# Generated by Django 3.2 on 2021-05-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_cowincenter_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrequest',
            name='notification_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
