# Generated by Django 3.2 on 2021-05-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alertrequest_notification_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertrequest',
            name='notification_counter',
        ),
        migrations.AddField(
            model_name='alertrequest',
            name='alerts_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
