# Generated by Django 3.2 on 2021-05-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210502_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertrequest',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='alertrequest',
            name='name',
        ),
    ]
