# Generated by Django 3.2 on 2021-05-02 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAlertMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid field')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('alert_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_sent', to='core.alertrequest')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_sent', to='core.cowinsession')),
            ],
            options={
                'unique_together': {('alert_request', 'session')},
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
