# Generated by Django 3.2 on 2021-05-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210502_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertrequest',
            name='age',
        ),
    ]
